const database = [
    {id: 'm1', num: '1', cat: 'Main', name: 'Pomegranate Peach', desc: 'Гранат Персик'},
    {id: 'm2', num: '2', cat: 'Main', name: 'Caribbean Set', desc: 'Микс тропических фруктов'},
    {id: 'm3', num: '3', cat: 'Main', name: 'Blueberry Cake', desc: 'Черничный пирог'},
    {id: 'm4', num: '4', cat: 'Main', name: 'Mocha Latte', desc: 'Мокка Латте'},
    {id: 'm5', num: '5', cat: 'Main', name: 'Strawberry Kiwi', desc: 'Клубника Киви'},
    {id: 'm6', num: '6', cat: 'Main', name: 'Cantaloupe Ice Cream', desc: 'Дыня Мороженое'},
    {id: 'm7', num: '7', cat: 'Main', name: 'Black Currant Marshmallow', desc: 'Черная смородина Зефир'},
    {id: 'm8', num: '8', cat: 'Main', name: 'Watermelon Bubble Gum', desc: 'Арбуз Жвачка'},
    {id: 'm9', num: '9', cat: 'Main', name: 'Strawberry Raspberry Soda', desc: 'Клубника Малина Сода'},
    {id: 'm10', num: '10', cat: 'Main', name: 'Sea Salt Lemon', desc: 'Морская соль Лимон'},
    {id: 'm11', num: '11', cat: 'Main', name: 'Rainbow Skittles', desc: 'Конфеты Скитлс'},
    {id: 'm12', num: '12', cat: 'Main', name: 'Pineapple Coconut', desc: 'Ананас Кокос'},
    {id: 'm13', num: '13', cat: 'Main', name: 'Kiwi Passion Guava', desc: 'Киви Маракуйя Гуава'},
    {id: 'm14', num: '14', cat: 'Main', name: 'Grapefruit Orange', desc: 'Грейпфрут Апельсин'},
    {id: 'm15', num: '15', cat: 'Main', name: 'Fanta Strawberry', desc: 'Клубника Фанта'},
    {id: 'm16', num: '16', cat: 'Main', name: 'Cranberry Grape', desc: 'Клюква Виноград'},
    {id: 'm17', num: '17', cat: 'Main', name: 'Cherry Tobacco', desc: 'Табак с вишней'},
    {id: 'm18', num: '18', cat: 'Main', name: 'Aloe Mango Honey', desc: 'Алоэ Манго Мед'},
    {id: 'm19', num: '19', cat: 'Main', name: 'Cherry Cola', desc: 'Вишневая кола'},
    {id: 'm20', num: '20', cat: 'Main', name: 'Mango Peach', desc: 'Манго Персик'},
    {id: 'm21', num: '21', cat: 'Main', name: 'Triple Melon Blast', desc: 'Тройная дыня'},
    {id: 'm22', num: '22', cat: 'Main', name: 'Triple Mango', desc: 'Тройной манго'},
    {id: 'm23', num: '23', cat: 'Main', name: 'Aloe Grape', desc: 'Алоэ Виноград'},
    {id: 'm24', num: '24', cat: 'Main', name: 'Double Apple', desc: 'Двойное яблоко'},
    {id: 'm25', num: '25', cat: 'Main', name: 'Strawberry Banana', desc: 'Клубника Банан'},
    {id: 'm26', num: '26', cat: 'Main', name: 'Strawberry Ice Cream', desc: 'Клубника Мороженое'},
    {id: 'm27', num: '27', cat: 'Main', name: 'Berries Watermelon', desc: 'Ягоды Арбуз'},
    {id: 'm28', num: '28', cat: 'Main', name: 'Passion Fruit Lime', desc: 'Маракуйя Лайм'},
    {id: 'm29', num: '29', cat: 'Main', name: 'Blue Razz', desc: 'Голубика черника малина'},
    {id: 'm30', num: '30', cat: 'Main', name: 'Virginia Tobacco', desc: 'Вирджиния табак'},
    {id: 'm31', num: '31', cat: 'Main', name: 'Butter Tobacco', desc: 'Табак с маслом'},
    {id: 'm32', num: '32', cat: 'Main', name: 'Nut Tobacco', desc: 'Ореховый табак'},
    {id: 'm33', num: '33', cat: 'Main', name: 'Fizzy Cherry', desc: 'Вишневая конфета'},
    {id: 'm34', num: '34', cat: 'Main', name: 'Strawberry Mango', desc: 'Клубника Манго'},
    {id: 'm35', num: '35', cat: 'Main', name: 'Cola Lime', desc: 'Кола Лайм'},
    {id: 'm36', num: '36', cat: 'Main', name: 'Citrus Black Tea', desc: 'Черный цитрусовый чай'},
    {id: 'm37', num: '37', cat: 'Main', name: 'Peach Ice', desc: 'Персик Лед'},
    {id: 'm38', num: '38', cat: 'Main', name: 'Pomegranate Plum Ice', desc: 'Гранат Слива Лед'},
    {id: 'm39', num: '39', cat: 'Main', name: 'Smooth Tobacco', desc: 'Карамельный Табак'},
    {id: 'm40', num: '40', cat: 'Main', name: 'White Peach Razz', desc: 'Персик Ягоды'},
    {id: 'm41', num: '41', cat: 'Main', name: 'Watermelon Cherry', desc: 'Арбуз Вишня'},
    {id: 'v2_10', num: '10', cat: 'V2', name: 'Malay Mango', desc: 'Малазийский Манго'},
    {id: 'v2_11', num: '11', cat: 'V2', name: 'Sour Pineapple Ice', desc: 'Кислый ананас Лед'},
    {id: 'v2_12', num: '12', cat: 'V2', name: 'Watermelon Lemon Berry', desc: 'Арбуз, Лимон, Лесные ягоды'},
    {id: 'v2_13', num: '13', cat: 'V2', name: 'Apple Shampagne', desc: 'Яблочное Шампанское'},
    {id: 'v2_14', num: '14', cat: 'V2', name: 'Blueberry Lemon Banana', desc: 'Черника, Лимон, Банан'},
    {id: 'v2_15', num: '15', cat: 'V2', name: 'Cucumber Pear', desc: 'Арбуз Дыня Огурец'},
    {id: 'v2_16', num: '16', cat: 'V2', name: 'Raspberry Mango Coconut', desc: 'Малина, Манго, Кокосовая вода'},
    {id: 'v2_17', num: '17', cat: 'V2', name: 'Green Grape Watermelon', desc: 'Зеленый виноград, Арбуз'},
    {id: 'n_5', num: '5', cat: 'No Ice', name: 'Strawberry Kiwi', desc: 'Клубника Киви (Без льда)'},
    {id: 'n_8', num: '8', cat: 'No Ice', name: 'Watermelon Bubble Gum', desc: 'Арбуз Жвачка (Без льда)'},
    {id: 'n_13', num: '13', cat: 'No Ice', name: 'Kiwi Passion Guava', desc: 'Киви Маракуйя Гуава (Без льда)'},
    {id: 'n_21', num: '21', cat: 'No Ice', name: 'Triple Melon Blast', desc: 'Тройная дыня (Без льда)'},
    {id: 'n_41', num: '41', cat: 'No Ice', name: 'Watermelon Cherry', desc: 'Арбуз Вишня (Без льда)'},
    {id: 'n_52', num: '52', cat: 'No Ice', name: 'Sakura Grape', desc: 'Сакура Виноград (Без льда)'},
    {id: 'std_1', num: '1', cat: 'Std', name: 'Miami Mint', desc: 'Свежая мята'},
    {id: 'std_2', num: '2', cat: 'Std', name: 'Lemon Cheesecake', desc: 'Лимонный чизкейк'},
    {id: 'std_3', num: '3', cat: 'Std', name: 'Guava Grapefruit', desc: 'Гуава Грейпфрут'},
    {id: 'std_4', num: '4', cat: 'Std', name: 'Kiwi Lime', desc: 'Киви Лайм'},
    {id: 'std_5', num: '5', cat: 'Std', name: 'Raspberry Peach', desc: 'Малина Персик'},
    {id: 'std_6', num: '6', cat: 'Std', name: 'Passion Martini', desc: 'Маракуйя Мартини'},
    {id: 'std_7', num: '7', cat: 'Std', name: 'Mentos Mint', desc: 'Конфеты Mentos'},
    {id: 'std_8', num: '8', cat: 'Std', name: 'Sour Cherry', desc: 'Кислая вишня'},
    {id: 'std_9', num: '9', cat: 'Std', name: 'Strawberry Rasp Cherry', desc: 'Клубника, Малина, Вишня, Лед'},
    {id: 'std_18', num: '18', cat: 'Std', name: 'Mango Berry Sorbet', desc: 'Щербет, Манго, Лесные ягоды'},
    {id: 'std_19', num: '19', cat: 'Std', name: 'Fresh Menthol Mojito', desc: 'Мятный Мохито'},
    {id: 'std_20', num: '20', cat: 'Std', name: 'Pink Wave', desc: 'Клубника, Апельсин, Кокос, Лимон'},
    {id: 'std_21', num: '21', cat: 'Std', name: 'Oreo Cookies', desc: 'Печенье Oreo'},
    {id: 'std_22', num: '22', cat: 'Std', name: 'Grape Mint', desc: 'Виноград, Мята'},
    {id: 'std_23', num: '23', cat: 'Std', name: 'Vanilla Tobacco', desc: 'Ванильный табак'},
    {id: 'std_24', num: '24', cat: 'Std', name: 'Orange Energy', desc: 'Апельсиновый энергетик'},
    {id: 'std_25', num: '25', cat: 'Std', name: 'Grape Energy', desc: 'Виноградный энергетик'},
    {id: 'std_26', num: '26', cat: 'Std', name: 'Tiger Blood', desc: 'Энергетик, Клубника, Арбуз, Кокос'}
];
